#ifndef ___SNAPSHOT_H__
#define ___SNAPSHOT_H__

#define GOOGLE_VSS_AGENT_SIG "GOOGVSS"

// DeviceIoControl functions of the driver.
#define SNAPSHOT_REQUESTED 0xE000
#define SNAPSHOT_CAN_PROCEED 0xE010
#define SNAPSHOT_DISCARD 0xE020

// Control codes for the DeviceIoContol functions of the driver.
#define IOCTL_SNAPSHOT_REQUESTED \
    CTL_CODE(SNAPSHOT_REQUESTED, 0x8FF, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SNAPSHOT_CAN_PROCEED \
    CTL_CODE(SNAPSHOT_CAN_PROCEED, 0x8FF, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SNAPSHOT_DISCARD \
    CTL_CODE(SNAPSHOT_DISCARD, 0x8FF, METHOD_NEITHER, FILE_ANY_ACCESS)
#endif  // ___VIOSCSI_H__
